version: '4'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    expose:
      - "8000:8000"

  character:
    container_name: Character
    restart: always
    build: ./characters
    expose:
      - ":8001"

  film:
    container_name: Film
    restart: always
    build: ./films
    expose:
      - ":8002"

  planet:
    container_name: Planet
    restart: always
    build: ./planets
    expose:
      - ":8003"
  
  database:
    container_name: database
    restart: always
    build: ./database
    expose:
      - ":8004"